enable AAD token authentication
prisma/tiberius pull request #215
Opened 2022-05-12 22:01 UTC by rogerpengyu

(https://github.com/prisma/tiberius/issues/175)

2022-05-13 19:56 UTC, pimeys requested changes
One thing missing: JDBC and ASP.net connection string parameters. Should be whatever Azure is using.

2022-05-13 19:56 UTC, pimeys commented on src/client/connection.rs
> +        let prelogin = connection
whitespace before this line

2022-05-13 19:56 UTC, pimeys commented on src/tds/codec/login.rs
> +        self.fed_auth_ext = Some(FedAuthExt {
whitespace before this line

2022-05-13 19:56 UTC, pimeys commented on src/tds/codec/token/token_feature_ext_ack.rs
> +#[derive(Debug)]
whitespace before this line

2022-05-14 00:36 UTC, rogerpengyu commented
> One thing missing: JDBC and ASP.net connection string parameters. Should be whatever Azure is using.

the connection string usually specifies AAD user name and secrets. Then it talks to AAD to retrieve a token. If we code that functionality in tiberious, we will need to include a http lib for token retrieval. I am trying to avoid that by just specifying the retrieved token. User could call AAD with their own code to retrieve the token. And call Config.aad_token() directly.

Let me know if you want to include the AAD token retrieval in tiberius

2022-05-15 14:18 UTC, pimeys commented
How do you get the token in Azure? I'm thinking about a public interface for Prisma users, who mainly configure SQL Server with the JDBC connection string. Can you get the token easily from Azure and how would it work then together with Tiberius?

2022-05-16 03:50 UTC, rogerpengyu commented
ODBC connection string could support (1) AAD user name + password; or (2) AAD service principal + secret. Both will take user id + secret from connection string, then making a REST API call to AAD to retrieve token, and pass the token to SQL server.

Calling AAD to retrieve token is straightforward, but it requires a HTTP client. Below is the code I used to retrieve token:

`        let token_body: Vec<u8> = form_urlencoded::Serializer::new(String::new())
            .append_pair("grant_type", "client_credentials")
            .append_pair("client_id", self.client_id.as_str())
            .append_pair("client_secret", self.client_secret.as_str())
            .append_pair("resource", self.resource_url.as_str())
            .finish()
            .into_bytes();
        let token_request = new_request()
            .method(Method::POST)
            .uri(format!("{}/{}/oauth2/token", self.authority_url, self.tenant_id))
            .header(HEADER_CONTENT_TYPE, CONTENT_TYPE_FORM_URLENCODED)
            .body(token_body)
            .expect("build token retrieval request should succeed");

        let res = self.http_client.clone().request(token_request.into())?.success()?;

        let token_body = String::from_utf8(res.into_body().to_vec()).expect("token response should always be utf8 encoded");
        let kvs: HashMap<String, String> = serde_json::from_str(token_body.as_str()).expect("token response should be valid json");

        let token = BearerToken(kvs["access_token"].to_string());
        let expired_on: Option<i64> = kvs.get("expires_on").map(|s| s.as_str().parse().unwrap());
`

There is not standard way to specify token in connection string directly. but one can specify the token in the properties for other sql client library. See https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15

"accessTokenStringnull | (Version 6.0+) Use this property to connect to a database using an access token. accessToken can't be set using the connection URL."

And this is how the lib works in java:

`        IAuthenticationResult authenticationResult = future.get();
        String accessToken = authenticationResult.accessToken();

        System.out.println("Access Token: " + accessToken);

        // Connect with the access token.
        SQLServerDataSource ds = new SQLServerDataSource();

        ds.setServerName("aad-managed-demo.database.windows.net"); // Replace with your server name.
        ds.setDatabaseName("demo"); // Replace with your database name.
        ds.setAccessToken(accessToken);`

So there are two options:
- enable userid/password in connection string, and include a HTTP client in tiberius;
- only supports token in tiberius, which cannot be specified by another interface than connection string

2022-05-16 07:33 UTC, pimeys commented
I think from the user perspective a HTTP client would make sense. The question is would it lock us to Tokio for good? Or could it be built so that we can still support other runtimes too?

I'm also thinking of a separate crate, such as `tiberius-aad` for the token retrieval. This makes sense when looking into the highly modular architecture of Tiberius, but we'd still need the connection string parsing to work, which might be tricky if the AAD stuff is in another crate.

2022-05-16 18:53 UTC, rogerpengyu commented
if we are ok to include a HTTP client, we could use reqwest, which is a synchronized lib (a good fit for your scenario as we only made very few http requests). it won't lock tiberius to async runtime as well.

let me know which way you want me to move. Either option (keep token only, or add reqwest to support password) will be ok to me.

2022-05-18 17:49 UTC, rogerpengyu commented
so what's the suggestion here?

2022-05-20 05:42 UTC, rogerpengyu commented
The azure-identity crate is just making the rest api call (see the code snippets I pasted above). If we all agree to include the token retrieval in Tiberius, that's one option.

@pimeys could you make the call here? Do you suggest to keep token retrieval in Tiberius (in which case we will depend on one http crate or azure identity crate)?

Or we can say Tiberius only support token as interface. Users are suggested to use azure-identify to retrieve token themselves.

2022-05-20 06:21 UTC, pimeys commented
Latter. But we need an example how to use it and docs.

2022-05-20 06:33 UTC, rogerpengyu commented
Sure. To be clear, that means one cannot use connect string to use AAD. They have to call the Config api to setup. Are you ok with that?

2022-05-23 05:10 UTC, rogerpengyu commented
on the doc string I add an example for token retrieval. @pimeys please take a look

2022-05-25 00:18 UTC, rogerpengyu commented
@pimeys : any other suggestions for the PR?

2022-05-26 17:50 UTC, rogerpengyu commented
ping @pimeys

2022-05-26 17:54 UTC, pimeys commented
On vacation. Back next week.

2022-05-31 08:07 UTC, pimeys commented on src/tds/codec/pre_login.rs
> +        fields.push((PRELOGIN_ENCTYPTION, 0x01)); // encryption
```suggestion
        fields.push((PRELOGIN_ENCRYPTION, 0x01)); // encryption
```

2022-05-31 08:11 UTC, pimeys commented on src/tds/codec/token/token_feature_ext_ack.rs
> +                    src.read_exact(&mut n).await?;
```suggestion
                    src.read_exact(&mut n).await?;

```

2022-05-31 08:11 UTC, pimeys commented on src/tds/codec/token/token_feature_ext_ack.rs
> +                };
```suggestion
                };

```

2022-05-31 22:44 UTC, rogerpengyu commented on src/tds/codec/login.rs
> +// pub const SESSIONRECOVERY: u8 = 0x01u8;
taken

2022-05-31 22:44 UTC, rogerpengyu commented on src/tds/codec/login.rs
> +pub const FEA_EXT_FEDAUTH: u8 = 0x02u8;
taken

2022-05-31 22:45 UTC, rogerpengyu commented on src/tds/codec/pre_login.rs
> +        fields.push((PRELOGIN_ENCTYPTION, 0x01)); // encryption
taken

2022-05-31 23:55 UTC, rogerpengyu commented on src/tds/codec/login.rs
> +mod tests {
I will suggest we keep this. It's difficult to setup integrated aad auth test. These are the only protection layer for code quality.

2022-05-31 23:58 UTC, rogerpengyu commented on src/tds/codec/login.rs
> +mod tests {
you don't have to read all the lines (as these are tests code), pretty much it runs a loopback test for serde and to check serialization could be correctly deserialized.

2022-06-01 00:01 UTC, rogerpengyu commented
all comments addressed. please take another look

2022-06-01 11:55 UTC, pimeys requested changes
Few nitpicks, but the tests must be green before merging.

2022-06-01 11:55 UTC, pimeys commented on examples/aad-auth.rs
> +    tcp.set_nodelay(true)?;
```suggestion
    tcp.set_nodelay(true)?;

```

2022-06-02 06:55 UTC, pimeys commented
Thank you, I'll cut a release.

2022-06-02 06:56 UTC, merged