Use GSSAPI for IntegratedSecurity on Unix
prisma/tiberius pull request #77
Opened 2020-08-15 20:46 UTC by dwink

This PR leverages the libgssapi crate to provide IntegratedSecurity support via Kerberos on Unix.

At the TDS protocol level, all the SSPI tokens/packets/etc are used for this, too, so I turned off the cfg(windows) for all of that machinery, and added the libgssapi dependency as cfg(unix). From a dependency perspective, though, could be nice to make it a dependency folks can turn off. Happy to adjust.

Anyhow, have a look and let me know what else this needs, if anything -- tested in a ActiveDirectory-based Kerberos environment with SQL Server.

2020-08-17 14:17 UTC, pimeys commented
You might want to change the ADO.net connection string handling and documentation to support this new method. I think we can live with the `IntegratedSecurity` param, but change the docs so it supports Kerberos too on Unix and the behavior of the param handling...

2020-08-17 14:20 UTC, pimeys commented
I think code-wise we could keep `WindowsIntegrated` for windows, but maybe consider renaming the new variant in the `AuthMethod`.

2020-08-17 15:55 UTC, dwink commented
> You might want to change the ADO.net connection string handling and documentation to support this new method. I think we can live with the `IntegratedSecurity` param, but change the docs so it supports Kerberos too on Unix and the behavior of the param handling...
> 
> https://docs.rs/tiberius/0.4.8/tiberius/struct.Config.html#method.from_ado_string

Ah, yes, totally missed that. Will do.

> I think code-wise we could keep `WindowsIntegrated` for windows, but maybe consider renaming the new variant in the `AuthMethod`.

Not quite sure I follow; what do you think the variant should be? I _think_ I could make WindowsIntegrated work on either `cfg(windows)` or `cfg(unix)` with flags, or keep it separate (as `Integrated`, or `Gssapi` or even `UnixIntegrated`)...

2020-08-24 13:14 UTC, esheppa approved these changes

2020-08-24 13:14 UTC, esheppa commented on Cargo.toml
> +libgssapi = "0.4"
Looks perfect, thanks very much!

2020-08-27 07:13 UTC, pimeys commented
Back to work. Doing my review round now, and when happy, merging and releasing the next Tiberius.

2020-08-27 07:57 UTC, pimeys requested changes
This seems to require a system library (on Linux at least) to compile the gssapi crate. I'm getting an error:

```
src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found
src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found, err: true
thread 'main' panicked at 'failed to generate gssapi bindings: ()', /home/pimeys/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.1/build.rs:54:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I couldn't find documentation on this PR how to install the correct packages, so would be nice to have a bit more info for our users what is required to get a successful compilation if using the feature.

I'm thinking of what support for Kerberos would mean in Prisma. How I understood this, for the client and server versions to work properly together the crate needs to be compiled against the correct version of libgssapi C library. This would mean providing a pre-compiled Prisma library from a CI system including the right headers would not work correctly if the user would have a different version in their system?

To make this PR right, we should be explicitly documenting the whole procedure to make it as easy as possible for our users to understand how the feature works.

2020-08-27 13:54 UTC, dwink commented
> This seems to require a system library (on Linux at least) to compile the gssapi crate. I'm getting an error:
> 
> ```
> src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found
> src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found, err: true
> thread 'main' panicked at 'failed to generate gssapi bindings: ()', /home/pimeys/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.1/build.rs:54:20
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> I couldn't find documentation on this PR how to install the correct packages, so would be nice to have a bit more info for our users what is required to get a successful compilation if using the feature.

Sure, I'll update the README with some more details.

> 
> I'm thinking of what support for Kerberos would mean in Prisma. How I understood this, for the client and server versions to work properly together the crate needs to be compiled against the correct version of libgssapi C library. This would mean providing a pre-compiled Prisma library from a CI system including the right headers would not work correctly if the user would have a different version in their system?
> 
> To make this PR right, we should be explicitly documenting the whole procedure to make it as easy as possible for our users to understand how the feature works.

The GSSAPI interface has been stable for more than a decade, so I wouldn't expect there to be too many breaking changes in the interface. Also, this feature does require some setup in the environment:
  *  an [SPN needs to be established for the server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/register-a-service-principal-name-for-kerberos-connections?view=sql-server-ver15). 
  * the Unix host needs to be trusted by the domain [here's RedHat's take](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/windows_integration_guide/adding-linux-to-ad)
  * the Unix host needs the kerberos workstation tools to get ticket-granting tickets (kinit, et al). 

In practice, organizations that would want to enable this feature for a system like Prisma would probably already have done this (as my organization has; I didn't think to document this because it Just Worked), as this is all the fundamental steps you need in order to join a Unix host to an Active Directory domain.

2020-08-28 12:44 UTC, pimeys commented
Pushed a few changes as a separate PR that would fix a few things. After these (or at least after a discussion about the changes) we're ready to go!

2020-08-29 10:16 UTC, merged

2020-08-29 10:16 UTC, pimeys commented
Thank you for this! I'll cut a new release today.